Jun-20 09:56:20.363 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf -c nextflow.config
Jun-20 09:56:20.490 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.4
Jun-20 09:56:20.545 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/trinity/home/c2006576/.nextflow/plugins; core-plugins: nf-amazon@2.5.3,nf-azure@1.6.1,nf-cloudcache@0.4.1,nf-codecommit@0.2.1,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2-patch1,nf-tower@1.9.1,nf-wave@1.4.2-patch1
Jun-20 09:56:20.559 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-20 09:56:20.560 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-20 09:56:20.564 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Jun-20 09:56:20.580 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-20 09:56:20.606 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/nextflow.config
Jun-20 09:56:20.609 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/nextflow.config
Jun-20 09:56:20.611 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/nextflow.config
Jun-20 09:56:20.611 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/nextflow.config
Jun-20 09:56:20.645 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /trinity/home/c2006576/.nextflow/secrets/store.json
Jun-20 09:56:20.648 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@3122b117] - activable => nextflow.secret.LocalSecretsProvider@3122b117
Jun-20 09:56:20.655 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-20 09:56:21.197 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-20 09:56:21.254 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Jun-20 09:56:21.273 [main] DEBUG nextflow.cli.CmdRun - Launching `main.nf` [astonishing_descartes] DSL2 - revision: 6e73952c61
Jun-20 09:56:21.275 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-20 09:56:21.275 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-20 09:56:21.346 [main] DEBUG nextflow.Session - Session UUID: 1306aba2-368a-402e-86a9-f00036b2875f
Jun-20 09:56:21.347 [main] DEBUG nextflow.Session - Run name: astonishing_descartes
Jun-20 09:56:21.347 [main] DEBUG nextflow.Session - Executor pool size: 12
Jun-20 09:56:21.357 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Jun-20 09:56:21.363 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=36; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jun-20 09:56:21.391 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.04.4 build 5917
  Created: 01-08-2024 07:05 UTC (08:05 BST)
  System: Linux 4.18.0-553.8.1.el8_10.x86_64
  Runtime: Groovy 4.0.21 on Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39
  Encoding: UTF-8 (UTF-8)
  Process: 1845575@iago.bios.cf.ac.uk [10.244.2.4]
  CPUs: 12 - Mem: 23.2 GB (189.7 MB) - Swap: 7.9 GB (7.4 GB)
Jun-20 09:56:21.420 [main] DEBUG nextflow.Session - Work-dir: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/work [nfs]
Jun-20 09:56:21.421 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/bin
Jun-20 09:56:21.432 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-20 09:56:21.443 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-20 09:56:21.473 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-20 09:56:21.487 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 13; maxThreads: 1000
Jun-20 09:56:21.563 [main] DEBUG nextflow.Session - Session start
Jun-20 09:56:21.870 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jun-20 09:56:22.273 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: slurm
Jun-20 09:56:22.274 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'slurm'
Jun-20 09:56:22.285 [main] DEBUG nextflow.executor.Executor - [warm up] executor > slurm
Jun-20 09:56:22.292 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'slurm' > capacity: 100; pollInterval: 5s; dumpInterval: 5m 
Jun-20 09:56:22.295 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: slurm)
Jun-20 09:56:22.298 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'slurm' > queue-stat-interval: 1m
Jun-20 09:56:22.368 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: antiSMASH_PREP, antiSMASH
Jun-20 09:56:22.369 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Jun-20 09:56:22.376 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > antiSMASH_PREP
Jun-20 09:56:22.377 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_35e5fd1f407a64e9: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/./modules/antiSMASH_PREP/main.nf
  Script_6672954015fe9a86: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/main.nf
  Script_8c5fbe5b49879365: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/./modules/antiSMASH/main.nf
Jun-20 09:56:22.379 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Jun-20 09:56:22.379 [main] DEBUG nextflow.Session - Session await
Jun-20 09:56:22.588 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process antiSMASH_PREP > jobId: 743129; workDir: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/work/d8/0bbb7701040a26b550eb1dda7611ac
Jun-20 09:56:22.589 [Task submitter] INFO  nextflow.Session - [d8/0bbb77] Submitted process > antiSMASH_PREP
Jun-20 09:56:27.310 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 743129; id: 1; name: antiSMASH_PREP; status: COMPLETED; exit: 1; error: -; workDir: /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/work/d8/0bbb7701040a26b550eb1dda7611ac started: 1750409787304; exited: 2025-06-20T08:56:26.221977887Z; ]
Jun-20 09:56:27.312 [Task monitor] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'TaskFinalizer' minSize=10; maxSize=36; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jun-20 09:56:27.320 [TaskFinalizer-1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=antiSMASH_PREP; work-dir=/mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/work/d8/0bbb7701040a26b550eb1dda7611ac
  error [nextflow.exception.ProcessFailedException]: Process `antiSMASH_PREP` terminated with an error exit status (1)
Jun-20 09:56:27.367 [TaskFinalizer-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'antiSMASH_PREP'

Caused by:
  Process `antiSMASH_PREP` terminated with an error exit status (1)


Command executed:

  download-antismash-databases --database-dir "data/database/antismashdb/"

Command exit status:
  1

Command output:
  
  Downloading antismash.js: 50.64% downloaded.
  Downloading antismash.js: 100.00% downloaded.
  Downloading PFAM version 35.0

Command error:
    File "/opt/conda/lib/python3.11/socket.py", line 863, in create_connection
      raise exceptions[0]
    File "/opt/conda/lib/python3.11/socket.py", line 848, in create_connection
      sock.connect(sa)
  ConnectionRefusedError: [Errno 111] Connection refused
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 133, in download_file
      req = request.urlopen(url)  # pylint: disable=consider-using-with
            ^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 519, in open
      response = self._open(req, data)
                 ^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 536, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 496, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 1391, in https_open
      return self.do_open(http.client.HTTPSConnection, req,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/urllib/request.py", line 1351, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/bin/download-antismash-databases", line 10, in <module>
      sys.exit(_main())
               ^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 553, in _main
      if not download(args):
             ^^^^^^^^^^^^^^
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 505, in download
      download_pfam(
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 285, in download_pfam
      download_if_not_present(url, archive_filename, archive_checksum)
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 234, in download_if_not_present
      download_file(url, filename)
    File "/opt/conda/lib/python3.11/site-packages/antismash/download_databases.py", line 135, in download_file
      raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
  antismash.download_databases.DownloadError: ERROR: File not found on server.
  Please check your internet connection.

Work dir:
  /mnt/scratch45/c2006576/Llyfrgell_Bersonol/nextflow/work/d8/0bbb7701040a26b550eb1dda7611ac

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Jun-20 09:56:27.374 [main] DEBUG nextflow.Session - Session await > all processes finished
Jun-20 09:56:27.377 [TaskFinalizer-1] DEBUG nextflow.Session - Session aborted -- Cause: Process `antiSMASH_PREP` terminated with an error exit status (1)
Jun-20 09:56:27.394 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: slurm) - terminating tasks monitor poll loop
Jun-20 09:56:27.394 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jun-20 09:56:27.406 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=5ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Jun-20 09:56:27.589 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jun-20 09:56:27.614 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
